name: Build and Deploy

on:
  push:
    branches:
      - main
      - cicd-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew
        working-directory: backend

      - name: Gradlew build
        run: |
          ./gradlew clean build -x test
        working-directory: backend

      - name: Insecure Docker Repository
        run: |
          sudo truncate -s-2 /etc/docker/daemon.json
          echo ", \"insecure-registries\": [\"${{ secrets.DOCKER_REGISTRY }}\"]}" | sudo tee -a /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Build and Push Docker Image
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE_NAME: trip-wizard-api
        run: |
          docker login ${{ secrets.DOCKER_REGISTRY }} --username ${{ secrets.DOCKER_USER_NAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/trip-wizard-api:${{ github.ref_name }} .
          docker push ${{ secrets.DOCKER_REGISTRY }}/trip-wizard-api:${{ github.ref_name }}
        working-directory: backend

      - name: Deploy with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            docker compose pull
            docker compose up -d
          working-directory: /root
